# Generated by Django 2.2.4 on 2020-05-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('job_desc', models.CharField(max_length=2000)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('project_desc', models.CharField(max_length=2000)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_username', models.CharField(max_length=50)),
                ('bid_amount', models.IntegerField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('bid_desc', models.CharField(max_length=2000)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Job_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_username', models.CharField(max_length=50)),
                ('hourly_rate', models.IntegerField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('appl_desc', models.CharField(max_length=2000)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.Jobs')),
            ],
        ),
    ]
